package com.jtm.mapper;

import com.jtm.dto.JBMatch;
import com.jtm.dto.JBMatchExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JBMatchMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	long countByExample(JBMatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	int deleteByExample(JBMatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	int deleteByPrimaryKey(Integer matchid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	int insert(JBMatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	int insertSelective(JBMatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	List<JBMatch> selectByExample(JBMatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	JBMatch selectByPrimaryKey(Integer matchid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	int updateByExampleSelective(@Param("record") JBMatch record, @Param("example") JBMatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	int updateByExample(@Param("record") JBMatch record, @Param("example") JBMatchExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	int updateByPrimaryKeySelective(JBMatch record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table jbmatch
	 * @mbg.generated  Thu Jan 31 16:25:24 CST 2019
	 */
	int updateByPrimaryKey(JBMatch record);
}