package com.jtm.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JBMatchExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public JBMatchExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMatchidIsNull() {
            addCriterion("MatchId is null");
            return (Criteria) this;
        }

        public Criteria andMatchidIsNotNull() {
            addCriterion("MatchId is not null");
            return (Criteria) this;
        }

        public Criteria andMatchidEqualTo(Integer value) {
            addCriterion("MatchId =", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidNotEqualTo(Integer value) {
            addCriterion("MatchId <>", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidGreaterThan(Integer value) {
            addCriterion("MatchId >", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidGreaterThanOrEqualTo(Integer value) {
            addCriterion("MatchId >=", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidLessThan(Integer value) {
            addCriterion("MatchId <", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidLessThanOrEqualTo(Integer value) {
            addCriterion("MatchId <=", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidIn(List<Integer> values) {
            addCriterion("MatchId in", values, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidNotIn(List<Integer> values) {
            addCriterion("MatchId not in", values, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidBetween(Integer value1, Integer value2) {
            addCriterion("MatchId between", value1, value2, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidNotBetween(Integer value1, Integer value2) {
            addCriterion("MatchId not between", value1, value2, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchnameIsNull() {
            addCriterion("MatchName is null");
            return (Criteria) this;
        }

        public Criteria andMatchnameIsNotNull() {
            addCriterion("MatchName is not null");
            return (Criteria) this;
        }

        public Criteria andMatchnameEqualTo(String value) {
            addCriterion("MatchName =", value, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameNotEqualTo(String value) {
            addCriterion("MatchName <>", value, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameGreaterThan(String value) {
            addCriterion("MatchName >", value, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameGreaterThanOrEqualTo(String value) {
            addCriterion("MatchName >=", value, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameLessThan(String value) {
            addCriterion("MatchName <", value, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameLessThanOrEqualTo(String value) {
            addCriterion("MatchName <=", value, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameLike(String value) {
            addCriterion("MatchName like", value, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameNotLike(String value) {
            addCriterion("MatchName not like", value, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameIn(List<String> values) {
            addCriterion("MatchName in", values, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameNotIn(List<String> values) {
            addCriterion("MatchName not in", values, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameBetween(String value1, String value2) {
            addCriterion("MatchName between", value1, value2, "matchname");
            return (Criteria) this;
        }

        public Criteria andMatchnameNotBetween(String value1, String value2) {
            addCriterion("MatchName not between", value1, value2, "matchname");
            return (Criteria) this;
        }

        public Criteria andNatchdateIsNull() {
            addCriterion("NatchDate is null");
            return (Criteria) this;
        }

        public Criteria andNatchdateIsNotNull() {
            addCriterion("NatchDate is not null");
            return (Criteria) this;
        }

        public Criteria andNatchdateEqualTo(Date value) {
            addCriterion("NatchDate =", value, "natchdate");
            return (Criteria) this;
        }

        public Criteria andNatchdateNotEqualTo(Date value) {
            addCriterion("NatchDate <>", value, "natchdate");
            return (Criteria) this;
        }

        public Criteria andNatchdateGreaterThan(Date value) {
            addCriterion("NatchDate >", value, "natchdate");
            return (Criteria) this;
        }

        public Criteria andNatchdateGreaterThanOrEqualTo(Date value) {
            addCriterion("NatchDate >=", value, "natchdate");
            return (Criteria) this;
        }

        public Criteria andNatchdateLessThan(Date value) {
            addCriterion("NatchDate <", value, "natchdate");
            return (Criteria) this;
        }

        public Criteria andNatchdateLessThanOrEqualTo(Date value) {
            addCriterion("NatchDate <=", value, "natchdate");
            return (Criteria) this;
        }

        public Criteria andNatchdateIn(List<Date> values) {
            addCriterion("NatchDate in", values, "natchdate");
            return (Criteria) this;
        }

        public Criteria andNatchdateNotIn(List<Date> values) {
            addCriterion("NatchDate not in", values, "natchdate");
            return (Criteria) this;
        }

        public Criteria andNatchdateBetween(Date value1, Date value2) {
            addCriterion("NatchDate between", value1, value2, "natchdate");
            return (Criteria) this;
        }

        public Criteria andNatchdateNotBetween(Date value1, Date value2) {
            addCriterion("NatchDate not between", value1, value2, "natchdate");
            return (Criteria) this;
        }

        public Criteria andRedteamIsNull() {
            addCriterion("RedTeam is null");
            return (Criteria) this;
        }

        public Criteria andRedteamIsNotNull() {
            addCriterion("RedTeam is not null");
            return (Criteria) this;
        }

        public Criteria andRedteamEqualTo(String value) {
            addCriterion("RedTeam =", value, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamNotEqualTo(String value) {
            addCriterion("RedTeam <>", value, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamGreaterThan(String value) {
            addCriterion("RedTeam >", value, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamGreaterThanOrEqualTo(String value) {
            addCriterion("RedTeam >=", value, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamLessThan(String value) {
            addCriterion("RedTeam <", value, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamLessThanOrEqualTo(String value) {
            addCriterion("RedTeam <=", value, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamLike(String value) {
            addCriterion("RedTeam like", value, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamNotLike(String value) {
            addCriterion("RedTeam not like", value, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamIn(List<String> values) {
            addCriterion("RedTeam in", values, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamNotIn(List<String> values) {
            addCriterion("RedTeam not in", values, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamBetween(String value1, String value2) {
            addCriterion("RedTeam between", value1, value2, "redteam");
            return (Criteria) this;
        }

        public Criteria andRedteamNotBetween(String value1, String value2) {
            addCriterion("RedTeam not between", value1, value2, "redteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamIsNull() {
            addCriterion("BuleTeam is null");
            return (Criteria) this;
        }

        public Criteria andBuleteamIsNotNull() {
            addCriterion("BuleTeam is not null");
            return (Criteria) this;
        }

        public Criteria andBuleteamEqualTo(String value) {
            addCriterion("BuleTeam =", value, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamNotEqualTo(String value) {
            addCriterion("BuleTeam <>", value, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamGreaterThan(String value) {
            addCriterion("BuleTeam >", value, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamGreaterThanOrEqualTo(String value) {
            addCriterion("BuleTeam >=", value, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamLessThan(String value) {
            addCriterion("BuleTeam <", value, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamLessThanOrEqualTo(String value) {
            addCriterion("BuleTeam <=", value, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamLike(String value) {
            addCriterion("BuleTeam like", value, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamNotLike(String value) {
            addCriterion("BuleTeam not like", value, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamIn(List<String> values) {
            addCriterion("BuleTeam in", values, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamNotIn(List<String> values) {
            addCriterion("BuleTeam not in", values, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamBetween(String value1, String value2) {
            addCriterion("BuleTeam between", value1, value2, "buleteam");
            return (Criteria) this;
        }

        public Criteria andBuleteamNotBetween(String value1, String value2) {
            addCriterion("BuleTeam not between", value1, value2, "buleteam");
            return (Criteria) this;
        }

        public Criteria andMatchresultIsNull() {
            addCriterion("MatchResult is null");
            return (Criteria) this;
        }

        public Criteria andMatchresultIsNotNull() {
            addCriterion("MatchResult is not null");
            return (Criteria) this;
        }

        public Criteria andMatchresultEqualTo(String value) {
            addCriterion("MatchResult =", value, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultNotEqualTo(String value) {
            addCriterion("MatchResult <>", value, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultGreaterThan(String value) {
            addCriterion("MatchResult >", value, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultGreaterThanOrEqualTo(String value) {
            addCriterion("MatchResult >=", value, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultLessThan(String value) {
            addCriterion("MatchResult <", value, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultLessThanOrEqualTo(String value) {
            addCriterion("MatchResult <=", value, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultLike(String value) {
            addCriterion("MatchResult like", value, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultNotLike(String value) {
            addCriterion("MatchResult not like", value, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultIn(List<String> values) {
            addCriterion("MatchResult in", values, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultNotIn(List<String> values) {
            addCriterion("MatchResult not in", values, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultBetween(String value1, String value2) {
            addCriterion("MatchResult between", value1, value2, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchresultNotBetween(String value1, String value2) {
            addCriterion("MatchResult not between", value1, value2, "matchresult");
            return (Criteria) this;
        }

        public Criteria andMatchvideoIsNull() {
            addCriterion("MatchVideo is null");
            return (Criteria) this;
        }

        public Criteria andMatchvideoIsNotNull() {
            addCriterion("MatchVideo is not null");
            return (Criteria) this;
        }

        public Criteria andMatchvideoEqualTo(String value) {
            addCriterion("MatchVideo =", value, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoNotEqualTo(String value) {
            addCriterion("MatchVideo <>", value, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoGreaterThan(String value) {
            addCriterion("MatchVideo >", value, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoGreaterThanOrEqualTo(String value) {
            addCriterion("MatchVideo >=", value, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoLessThan(String value) {
            addCriterion("MatchVideo <", value, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoLessThanOrEqualTo(String value) {
            addCriterion("MatchVideo <=", value, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoLike(String value) {
            addCriterion("MatchVideo like", value, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoNotLike(String value) {
            addCriterion("MatchVideo not like", value, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoIn(List<String> values) {
            addCriterion("MatchVideo in", values, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoNotIn(List<String> values) {
            addCriterion("MatchVideo not in", values, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoBetween(String value1, String value2) {
            addCriterion("MatchVideo between", value1, value2, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMatchvideoNotBetween(String value1, String value2) {
            addCriterion("MatchVideo not between", value1, value2, "matchvideo");
            return (Criteria) this;
        }

        public Criteria andMaketimeIsNull() {
            addCriterion("MakeTime is null");
            return (Criteria) this;
        }

        public Criteria andMaketimeIsNotNull() {
            addCriterion("MakeTime is not null");
            return (Criteria) this;
        }

        public Criteria andMaketimeEqualTo(Date value) {
            addCriterion("MakeTime =", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotEqualTo(Date value) {
            addCriterion("MakeTime <>", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeGreaterThan(Date value) {
            addCriterion("MakeTime >", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MakeTime >=", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeLessThan(Date value) {
            addCriterion("MakeTime <", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeLessThanOrEqualTo(Date value) {
            addCriterion("MakeTime <=", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeIn(List<Date> values) {
            addCriterion("MakeTime in", values, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotIn(List<Date> values) {
            addCriterion("MakeTime not in", values, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeBetween(Date value1, Date value2) {
            addCriterion("MakeTime between", value1, value2, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotBetween(Date value1, Date value2) {
            addCriterion("MakeTime not between", value1, value2, "maketime");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNull() {
            addCriterion("ModifyTime is null");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNotNull() {
            addCriterion("ModifyTime is not null");
            return (Criteria) this;
        }

        public Criteria andModifytimeEqualTo(Date value) {
            addCriterion("ModifyTime =", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotEqualTo(Date value) {
            addCriterion("ModifyTime <>", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThan(Date value) {
            addCriterion("ModifyTime >", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ModifyTime >=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThan(Date value) {
            addCriterion("ModifyTime <", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThanOrEqualTo(Date value) {
            addCriterion("ModifyTime <=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeIn(List<Date> values) {
            addCriterion("ModifyTime in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotIn(List<Date> values) {
            addCriterion("ModifyTime not in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeBetween(Date value1, Date value2) {
            addCriterion("ModifyTime between", value1, value2, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotBetween(Date value1, Date value2) {
            addCriterion("ModifyTime not between", value1, value2, "modifytime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jbmatch
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 27 21:07:30 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}