package com.jtm.dto;

import java.util.Date;

public class JBMatch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbmatch.MatchId
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    private Integer matchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbmatch.MatchName
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    private String matchname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbmatch.NatchDate
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    private Date natchdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbmatch.RedTeam
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    private String redteam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbmatch.BuleTeam
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    private String buleteam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbmatch.MatchResult
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    private String matchresult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbmatch.MatchVideo
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    private String matchvideo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbmatch.MakeTime
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    private Date maketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbmatch.ModifyTime
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbmatch.MatchId
     *
     * @return the value of jbmatch.MatchId
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public Integer getMatchid() {
        return matchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbmatch.MatchId
     *
     * @param matchid the value for jbmatch.MatchId
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setMatchid(Integer matchid) {
        this.matchid = matchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbmatch.MatchName
     *
     * @return the value of jbmatch.MatchName
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public String getMatchname() {
        return matchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbmatch.MatchName
     *
     * @param matchname the value for jbmatch.MatchName
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setMatchname(String matchname) {
        this.matchname = matchname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbmatch.NatchDate
     *
     * @return the value of jbmatch.NatchDate
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public Date getNatchdate() {
        return natchdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbmatch.NatchDate
     *
     * @param natchdate the value for jbmatch.NatchDate
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setNatchdate(Date natchdate) {
        this.natchdate = natchdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbmatch.RedTeam
     *
     * @return the value of jbmatch.RedTeam
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public String getRedteam() {
        return redteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbmatch.RedTeam
     *
     * @param redteam the value for jbmatch.RedTeam
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setRedteam(String redteam) {
        this.redteam = redteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbmatch.BuleTeam
     *
     * @return the value of jbmatch.BuleTeam
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public String getBuleteam() {
        return buleteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbmatch.BuleTeam
     *
     * @param buleteam the value for jbmatch.BuleTeam
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setBuleteam(String buleteam) {
        this.buleteam = buleteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbmatch.MatchResult
     *
     * @return the value of jbmatch.MatchResult
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public String getMatchresult() {
        return matchresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbmatch.MatchResult
     *
     * @param matchresult the value for jbmatch.MatchResult
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setMatchresult(String matchresult) {
        this.matchresult = matchresult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbmatch.MatchVideo
     *
     * @return the value of jbmatch.MatchVideo
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public String getMatchvideo() {
        return matchvideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbmatch.MatchVideo
     *
     * @param matchvideo the value for jbmatch.MatchVideo
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setMatchvideo(String matchvideo) {
        this.matchvideo = matchvideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbmatch.MakeTime
     *
     * @return the value of jbmatch.MakeTime
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public Date getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbmatch.MakeTime
     *
     * @param maketime the value for jbmatch.MakeTime
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbmatch.ModifyTime
     *
     * @return the value of jbmatch.ModifyTime
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbmatch.ModifyTime
     *
     * @param modifytime the value for jbmatch.ModifyTime
     *
     * @mbggenerated Wed Nov 27 21:07:30 CST 2019
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}