package com.jtm.dto;

import java.util.Date;

public class JBPlayer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbplayer.Playerid
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Integer playerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbplayer.Playername
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String playername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbplayer.Playersex
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String playersex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbplayer.Playerbirthday
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Date playerbirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbplayer.Entrytime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbplayer.Workflag
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String workflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbplayer.quittime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Date quittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbplayer.Entryteam
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Date entryteam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbplayer.MakeTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Date maketime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbplayer.ModifyTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbplayer.Playerid
     *
     * @return the value of jbplayer.Playerid
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbplayer.Playerid
     *
     * @param playerid the value for jbplayer.Playerid
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbplayer.Playername
     *
     * @return the value of jbplayer.Playername
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getPlayername() {
        return playername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbplayer.Playername
     *
     * @param playername the value for jbplayer.Playername
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setPlayername(String playername) {
        this.playername = playername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbplayer.Playersex
     *
     * @return the value of jbplayer.Playersex
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getPlayersex() {
        return playersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbplayer.Playersex
     *
     * @param playersex the value for jbplayer.Playersex
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setPlayersex(String playersex) {
        this.playersex = playersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbplayer.Playerbirthday
     *
     * @return the value of jbplayer.Playerbirthday
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Date getPlayerbirthday() {
        return playerbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbplayer.Playerbirthday
     *
     * @param playerbirthday the value for jbplayer.Playerbirthday
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setPlayerbirthday(Date playerbirthday) {
        this.playerbirthday = playerbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbplayer.Entrytime
     *
     * @return the value of jbplayer.Entrytime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbplayer.Entrytime
     *
     * @param entrytime the value for jbplayer.Entrytime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setEntrytime(String entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbplayer.Workflag
     *
     * @return the value of jbplayer.Workflag
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getWorkflag() {
        return workflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbplayer.Workflag
     *
     * @param workflag the value for jbplayer.Workflag
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setWorkflag(String workflag) {
        this.workflag = workflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbplayer.quittime
     *
     * @return the value of jbplayer.quittime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Date getQuittime() {
        return quittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbplayer.quittime
     *
     * @param quittime the value for jbplayer.quittime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setQuittime(Date quittime) {
        this.quittime = quittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbplayer.Entryteam
     *
     * @return the value of jbplayer.Entryteam
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Date getEntryteam() {
        return entryteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbplayer.Entryteam
     *
     * @param entryteam the value for jbplayer.Entryteam
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setEntryteam(Date entryteam) {
        this.entryteam = entryteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbplayer.MakeTime
     *
     * @return the value of jbplayer.MakeTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Date getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbplayer.MakeTime
     *
     * @param maketime the value for jbplayer.MakeTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbplayer.ModifyTime
     *
     * @return the value of jbplayer.ModifyTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbplayer.ModifyTime
     *
     * @param modifytime the value for jbplayer.ModifyTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}