package com.jtm.dto;

public class JBSiglePlayerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Playerid
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    private Integer playerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Matchid
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    private Integer matchid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Playerid
     *
     * @return the value of jbsigleplayer.Playerid
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public Integer getPlayerid() {
        return playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Playerid
     *
     * @param playerid the value for jbsigleplayer.Playerid
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public void setPlayerid(Integer playerid) {
        this.playerid = playerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Matchid
     *
     * @return the value of jbsigleplayer.Matchid
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public Integer getMatchid() {
        return matchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Matchid
     *
     * @param matchid the value for jbsigleplayer.Matchid
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public void setMatchid(Integer matchid) {
        this.matchid = matchid;
    }
}