package com.jtm.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JBSiglePlayerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public JBSiglePlayerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlayeridIsNull() {
            addCriterion("Playerid is null");
            return (Criteria) this;
        }

        public Criteria andPlayeridIsNotNull() {
            addCriterion("Playerid is not null");
            return (Criteria) this;
        }

        public Criteria andPlayeridEqualTo(Integer value) {
            addCriterion("Playerid =", value, "playerid");
            return (Criteria) this;
        }

        public Criteria andPlayeridNotEqualTo(Integer value) {
            addCriterion("Playerid <>", value, "playerid");
            return (Criteria) this;
        }

        public Criteria andPlayeridGreaterThan(Integer value) {
            addCriterion("Playerid >", value, "playerid");
            return (Criteria) this;
        }

        public Criteria andPlayeridGreaterThanOrEqualTo(Integer value) {
            addCriterion("Playerid >=", value, "playerid");
            return (Criteria) this;
        }

        public Criteria andPlayeridLessThan(Integer value) {
            addCriterion("Playerid <", value, "playerid");
            return (Criteria) this;
        }

        public Criteria andPlayeridLessThanOrEqualTo(Integer value) {
            addCriterion("Playerid <=", value, "playerid");
            return (Criteria) this;
        }

        public Criteria andPlayeridIn(List<Integer> values) {
            addCriterion("Playerid in", values, "playerid");
            return (Criteria) this;
        }

        public Criteria andPlayeridNotIn(List<Integer> values) {
            addCriterion("Playerid not in", values, "playerid");
            return (Criteria) this;
        }

        public Criteria andPlayeridBetween(Integer value1, Integer value2) {
            addCriterion("Playerid between", value1, value2, "playerid");
            return (Criteria) this;
        }

        public Criteria andPlayeridNotBetween(Integer value1, Integer value2) {
            addCriterion("Playerid not between", value1, value2, "playerid");
            return (Criteria) this;
        }

        public Criteria andMatchidIsNull() {
            addCriterion("Matchid is null");
            return (Criteria) this;
        }

        public Criteria andMatchidIsNotNull() {
            addCriterion("Matchid is not null");
            return (Criteria) this;
        }

        public Criteria andMatchidEqualTo(Integer value) {
            addCriterion("Matchid =", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidNotEqualTo(Integer value) {
            addCriterion("Matchid <>", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidGreaterThan(Integer value) {
            addCriterion("Matchid >", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Matchid >=", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidLessThan(Integer value) {
            addCriterion("Matchid <", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidLessThanOrEqualTo(Integer value) {
            addCriterion("Matchid <=", value, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidIn(List<Integer> values) {
            addCriterion("Matchid in", values, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidNotIn(List<Integer> values) {
            addCriterion("Matchid not in", values, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidBetween(Integer value1, Integer value2) {
            addCriterion("Matchid between", value1, value2, "matchid");
            return (Criteria) this;
        }

        public Criteria andMatchidNotBetween(Integer value1, Integer value2) {
            addCriterion("Matchid not between", value1, value2, "matchid");
            return (Criteria) this;
        }

        public Criteria andPlayernameIsNull() {
            addCriterion("Playername is null");
            return (Criteria) this;
        }

        public Criteria andPlayernameIsNotNull() {
            addCriterion("Playername is not null");
            return (Criteria) this;
        }

        public Criteria andPlayernameEqualTo(String value) {
            addCriterion("Playername =", value, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameNotEqualTo(String value) {
            addCriterion("Playername <>", value, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameGreaterThan(String value) {
            addCriterion("Playername >", value, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameGreaterThanOrEqualTo(String value) {
            addCriterion("Playername >=", value, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameLessThan(String value) {
            addCriterion("Playername <", value, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameLessThanOrEqualTo(String value) {
            addCriterion("Playername <=", value, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameLike(String value) {
            addCriterion("Playername like", value, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameNotLike(String value) {
            addCriterion("Playername not like", value, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameIn(List<String> values) {
            addCriterion("Playername in", values, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameNotIn(List<String> values) {
            addCriterion("Playername not in", values, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameBetween(String value1, String value2) {
            addCriterion("Playername between", value1, value2, "playername");
            return (Criteria) this;
        }

        public Criteria andPlayernameNotBetween(String value1, String value2) {
            addCriterion("Playername not between", value1, value2, "playername");
            return (Criteria) this;
        }

        public Criteria andMatchteamIsNull() {
            addCriterion("Matchteam is null");
            return (Criteria) this;
        }

        public Criteria andMatchteamIsNotNull() {
            addCriterion("Matchteam is not null");
            return (Criteria) this;
        }

        public Criteria andMatchteamEqualTo(String value) {
            addCriterion("Matchteam =", value, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamNotEqualTo(String value) {
            addCriterion("Matchteam <>", value, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamGreaterThan(String value) {
            addCriterion("Matchteam >", value, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamGreaterThanOrEqualTo(String value) {
            addCriterion("Matchteam >=", value, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamLessThan(String value) {
            addCriterion("Matchteam <", value, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamLessThanOrEqualTo(String value) {
            addCriterion("Matchteam <=", value, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamLike(String value) {
            addCriterion("Matchteam like", value, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamNotLike(String value) {
            addCriterion("Matchteam not like", value, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamIn(List<String> values) {
            addCriterion("Matchteam in", values, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamNotIn(List<String> values) {
            addCriterion("Matchteam not in", values, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamBetween(String value1, String value2) {
            addCriterion("Matchteam between", value1, value2, "matchteam");
            return (Criteria) this;
        }

        public Criteria andMatchteamNotBetween(String value1, String value2) {
            addCriterion("Matchteam not between", value1, value2, "matchteam");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidIsNull() {
            addCriterion("Playerheroid is null");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidIsNotNull() {
            addCriterion("Playerheroid is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidEqualTo(Integer value) {
            addCriterion("Playerheroid =", value, "playerheroid");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidNotEqualTo(Integer value) {
            addCriterion("Playerheroid <>", value, "playerheroid");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidGreaterThan(Integer value) {
            addCriterion("Playerheroid >", value, "playerheroid");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Playerheroid >=", value, "playerheroid");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidLessThan(Integer value) {
            addCriterion("Playerheroid <", value, "playerheroid");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidLessThanOrEqualTo(Integer value) {
            addCriterion("Playerheroid <=", value, "playerheroid");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidIn(List<Integer> values) {
            addCriterion("Playerheroid in", values, "playerheroid");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidNotIn(List<Integer> values) {
            addCriterion("Playerheroid not in", values, "playerheroid");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidBetween(Integer value1, Integer value2) {
            addCriterion("Playerheroid between", value1, value2, "playerheroid");
            return (Criteria) this;
        }

        public Criteria andPlayerheroidNotBetween(Integer value1, Integer value2) {
            addCriterion("Playerheroid not between", value1, value2, "playerheroid");
            return (Criteria) this;
        }

        public Criteria andPlayerheroIsNull() {
            addCriterion("Playerhero is null");
            return (Criteria) this;
        }

        public Criteria andPlayerheroIsNotNull() {
            addCriterion("Playerhero is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerheroEqualTo(String value) {
            addCriterion("Playerhero =", value, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroNotEqualTo(String value) {
            addCriterion("Playerhero <>", value, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroGreaterThan(String value) {
            addCriterion("Playerhero >", value, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroGreaterThanOrEqualTo(String value) {
            addCriterion("Playerhero >=", value, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroLessThan(String value) {
            addCriterion("Playerhero <", value, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroLessThanOrEqualTo(String value) {
            addCriterion("Playerhero <=", value, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroLike(String value) {
            addCriterion("Playerhero like", value, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroNotLike(String value) {
            addCriterion("Playerhero not like", value, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroIn(List<String> values) {
            addCriterion("Playerhero in", values, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroNotIn(List<String> values) {
            addCriterion("Playerhero not in", values, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroBetween(String value1, String value2) {
            addCriterion("Playerhero between", value1, value2, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerheroNotBetween(String value1, String value2) {
            addCriterion("Playerhero not between", value1, value2, "playerhero");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1IsNull() {
            addCriterion("Playerskill1 is null");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1IsNotNull() {
            addCriterion("Playerskill1 is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1EqualTo(String value) {
            addCriterion("Playerskill1 =", value, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1NotEqualTo(String value) {
            addCriterion("Playerskill1 <>", value, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1GreaterThan(String value) {
            addCriterion("Playerskill1 >", value, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1GreaterThanOrEqualTo(String value) {
            addCriterion("Playerskill1 >=", value, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1LessThan(String value) {
            addCriterion("Playerskill1 <", value, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1LessThanOrEqualTo(String value) {
            addCriterion("Playerskill1 <=", value, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1Like(String value) {
            addCriterion("Playerskill1 like", value, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1NotLike(String value) {
            addCriterion("Playerskill1 not like", value, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1In(List<String> values) {
            addCriterion("Playerskill1 in", values, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1NotIn(List<String> values) {
            addCriterion("Playerskill1 not in", values, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1Between(String value1, String value2) {
            addCriterion("Playerskill1 between", value1, value2, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill1NotBetween(String value1, String value2) {
            addCriterion("Playerskill1 not between", value1, value2, "playerskill1");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2IsNull() {
            addCriterion("Playerskill2 is null");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2IsNotNull() {
            addCriterion("Playerskill2 is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2EqualTo(String value) {
            addCriterion("Playerskill2 =", value, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2NotEqualTo(String value) {
            addCriterion("Playerskill2 <>", value, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2GreaterThan(String value) {
            addCriterion("Playerskill2 >", value, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2GreaterThanOrEqualTo(String value) {
            addCriterion("Playerskill2 >=", value, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2LessThan(String value) {
            addCriterion("Playerskill2 <", value, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2LessThanOrEqualTo(String value) {
            addCriterion("Playerskill2 <=", value, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2Like(String value) {
            addCriterion("Playerskill2 like", value, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2NotLike(String value) {
            addCriterion("Playerskill2 not like", value, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2In(List<String> values) {
            addCriterion("Playerskill2 in", values, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2NotIn(List<String> values) {
            addCriterion("Playerskill2 not in", values, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2Between(String value1, String value2) {
            addCriterion("Playerskill2 between", value1, value2, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andPlayerskill2NotBetween(String value1, String value2) {
            addCriterion("Playerskill2 not between", value1, value2, "playerskill2");
            return (Criteria) this;
        }

        public Criteria andOrnamentIsNull() {
            addCriterion("Ornament is null");
            return (Criteria) this;
        }

        public Criteria andOrnamentIsNotNull() {
            addCriterion("Ornament is not null");
            return (Criteria) this;
        }

        public Criteria andOrnamentEqualTo(String value) {
            addCriterion("Ornament =", value, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentNotEqualTo(String value) {
            addCriterion("Ornament <>", value, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentGreaterThan(String value) {
            addCriterion("Ornament >", value, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentGreaterThanOrEqualTo(String value) {
            addCriterion("Ornament >=", value, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentLessThan(String value) {
            addCriterion("Ornament <", value, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentLessThanOrEqualTo(String value) {
            addCriterion("Ornament <=", value, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentLike(String value) {
            addCriterion("Ornament like", value, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentNotLike(String value) {
            addCriterion("Ornament not like", value, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentIn(List<String> values) {
            addCriterion("Ornament in", values, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentNotIn(List<String> values) {
            addCriterion("Ornament not in", values, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentBetween(String value1, String value2) {
            addCriterion("Ornament between", value1, value2, "ornament");
            return (Criteria) this;
        }

        public Criteria andOrnamentNotBetween(String value1, String value2) {
            addCriterion("Ornament not between", value1, value2, "ornament");
            return (Criteria) this;
        }

        public Criteria andEquipment1IsNull() {
            addCriterion("Equipment1 is null");
            return (Criteria) this;
        }

        public Criteria andEquipment1IsNotNull() {
            addCriterion("Equipment1 is not null");
            return (Criteria) this;
        }

        public Criteria andEquipment1EqualTo(String value) {
            addCriterion("Equipment1 =", value, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1NotEqualTo(String value) {
            addCriterion("Equipment1 <>", value, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1GreaterThan(String value) {
            addCriterion("Equipment1 >", value, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1GreaterThanOrEqualTo(String value) {
            addCriterion("Equipment1 >=", value, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1LessThan(String value) {
            addCriterion("Equipment1 <", value, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1LessThanOrEqualTo(String value) {
            addCriterion("Equipment1 <=", value, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1Like(String value) {
            addCriterion("Equipment1 like", value, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1NotLike(String value) {
            addCriterion("Equipment1 not like", value, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1In(List<String> values) {
            addCriterion("Equipment1 in", values, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1NotIn(List<String> values) {
            addCriterion("Equipment1 not in", values, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1Between(String value1, String value2) {
            addCriterion("Equipment1 between", value1, value2, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment1NotBetween(String value1, String value2) {
            addCriterion("Equipment1 not between", value1, value2, "equipment1");
            return (Criteria) this;
        }

        public Criteria andEquipment2IsNull() {
            addCriterion("Equipment2 is null");
            return (Criteria) this;
        }

        public Criteria andEquipment2IsNotNull() {
            addCriterion("Equipment2 is not null");
            return (Criteria) this;
        }

        public Criteria andEquipment2EqualTo(String value) {
            addCriterion("Equipment2 =", value, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2NotEqualTo(String value) {
            addCriterion("Equipment2 <>", value, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2GreaterThan(String value) {
            addCriterion("Equipment2 >", value, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2GreaterThanOrEqualTo(String value) {
            addCriterion("Equipment2 >=", value, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2LessThan(String value) {
            addCriterion("Equipment2 <", value, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2LessThanOrEqualTo(String value) {
            addCriterion("Equipment2 <=", value, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2Like(String value) {
            addCriterion("Equipment2 like", value, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2NotLike(String value) {
            addCriterion("Equipment2 not like", value, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2In(List<String> values) {
            addCriterion("Equipment2 in", values, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2NotIn(List<String> values) {
            addCriterion("Equipment2 not in", values, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2Between(String value1, String value2) {
            addCriterion("Equipment2 between", value1, value2, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment2NotBetween(String value1, String value2) {
            addCriterion("Equipment2 not between", value1, value2, "equipment2");
            return (Criteria) this;
        }

        public Criteria andEquipment3IsNull() {
            addCriterion("Equipment3 is null");
            return (Criteria) this;
        }

        public Criteria andEquipment3IsNotNull() {
            addCriterion("Equipment3 is not null");
            return (Criteria) this;
        }

        public Criteria andEquipment3EqualTo(String value) {
            addCriterion("Equipment3 =", value, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3NotEqualTo(String value) {
            addCriterion("Equipment3 <>", value, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3GreaterThan(String value) {
            addCriterion("Equipment3 >", value, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3GreaterThanOrEqualTo(String value) {
            addCriterion("Equipment3 >=", value, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3LessThan(String value) {
            addCriterion("Equipment3 <", value, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3LessThanOrEqualTo(String value) {
            addCriterion("Equipment3 <=", value, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3Like(String value) {
            addCriterion("Equipment3 like", value, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3NotLike(String value) {
            addCriterion("Equipment3 not like", value, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3In(List<String> values) {
            addCriterion("Equipment3 in", values, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3NotIn(List<String> values) {
            addCriterion("Equipment3 not in", values, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3Between(String value1, String value2) {
            addCriterion("Equipment3 between", value1, value2, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment3NotBetween(String value1, String value2) {
            addCriterion("Equipment3 not between", value1, value2, "equipment3");
            return (Criteria) this;
        }

        public Criteria andEquipment4IsNull() {
            addCriterion("Equipment4 is null");
            return (Criteria) this;
        }

        public Criteria andEquipment4IsNotNull() {
            addCriterion("Equipment4 is not null");
            return (Criteria) this;
        }

        public Criteria andEquipment4EqualTo(String value) {
            addCriterion("Equipment4 =", value, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4NotEqualTo(String value) {
            addCriterion("Equipment4 <>", value, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4GreaterThan(String value) {
            addCriterion("Equipment4 >", value, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4GreaterThanOrEqualTo(String value) {
            addCriterion("Equipment4 >=", value, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4LessThan(String value) {
            addCriterion("Equipment4 <", value, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4LessThanOrEqualTo(String value) {
            addCriterion("Equipment4 <=", value, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4Like(String value) {
            addCriterion("Equipment4 like", value, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4NotLike(String value) {
            addCriterion("Equipment4 not like", value, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4In(List<String> values) {
            addCriterion("Equipment4 in", values, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4NotIn(List<String> values) {
            addCriterion("Equipment4 not in", values, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4Between(String value1, String value2) {
            addCriterion("Equipment4 between", value1, value2, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment4NotBetween(String value1, String value2) {
            addCriterion("Equipment4 not between", value1, value2, "equipment4");
            return (Criteria) this;
        }

        public Criteria andEquipment5IsNull() {
            addCriterion("Equipment5 is null");
            return (Criteria) this;
        }

        public Criteria andEquipment5IsNotNull() {
            addCriterion("Equipment5 is not null");
            return (Criteria) this;
        }

        public Criteria andEquipment5EqualTo(String value) {
            addCriterion("Equipment5 =", value, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5NotEqualTo(String value) {
            addCriterion("Equipment5 <>", value, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5GreaterThan(String value) {
            addCriterion("Equipment5 >", value, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5GreaterThanOrEqualTo(String value) {
            addCriterion("Equipment5 >=", value, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5LessThan(String value) {
            addCriterion("Equipment5 <", value, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5LessThanOrEqualTo(String value) {
            addCriterion("Equipment5 <=", value, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5Like(String value) {
            addCriterion("Equipment5 like", value, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5NotLike(String value) {
            addCriterion("Equipment5 not like", value, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5In(List<String> values) {
            addCriterion("Equipment5 in", values, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5NotIn(List<String> values) {
            addCriterion("Equipment5 not in", values, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5Between(String value1, String value2) {
            addCriterion("Equipment5 between", value1, value2, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment5NotBetween(String value1, String value2) {
            addCriterion("Equipment5 not between", value1, value2, "equipment5");
            return (Criteria) this;
        }

        public Criteria andEquipment6IsNull() {
            addCriterion("Equipment6 is null");
            return (Criteria) this;
        }

        public Criteria andEquipment6IsNotNull() {
            addCriterion("Equipment6 is not null");
            return (Criteria) this;
        }

        public Criteria andEquipment6EqualTo(String value) {
            addCriterion("Equipment6 =", value, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6NotEqualTo(String value) {
            addCriterion("Equipment6 <>", value, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6GreaterThan(String value) {
            addCriterion("Equipment6 >", value, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6GreaterThanOrEqualTo(String value) {
            addCriterion("Equipment6 >=", value, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6LessThan(String value) {
            addCriterion("Equipment6 <", value, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6LessThanOrEqualTo(String value) {
            addCriterion("Equipment6 <=", value, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6Like(String value) {
            addCriterion("Equipment6 like", value, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6NotLike(String value) {
            addCriterion("Equipment6 not like", value, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6In(List<String> values) {
            addCriterion("Equipment6 in", values, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6NotIn(List<String> values) {
            addCriterion("Equipment6 not in", values, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6Between(String value1, String value2) {
            addCriterion("Equipment6 between", value1, value2, "equipment6");
            return (Criteria) this;
        }

        public Criteria andEquipment6NotBetween(String value1, String value2) {
            addCriterion("Equipment6 not between", value1, value2, "equipment6");
            return (Criteria) this;
        }

        public Criteria andKillnumberIsNull() {
            addCriterion("Killnumber is null");
            return (Criteria) this;
        }

        public Criteria andKillnumberIsNotNull() {
            addCriterion("Killnumber is not null");
            return (Criteria) this;
        }

        public Criteria andKillnumberEqualTo(Integer value) {
            addCriterion("Killnumber =", value, "killnumber");
            return (Criteria) this;
        }

        public Criteria andKillnumberNotEqualTo(Integer value) {
            addCriterion("Killnumber <>", value, "killnumber");
            return (Criteria) this;
        }

        public Criteria andKillnumberGreaterThan(Integer value) {
            addCriterion("Killnumber >", value, "killnumber");
            return (Criteria) this;
        }

        public Criteria andKillnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("Killnumber >=", value, "killnumber");
            return (Criteria) this;
        }

        public Criteria andKillnumberLessThan(Integer value) {
            addCriterion("Killnumber <", value, "killnumber");
            return (Criteria) this;
        }

        public Criteria andKillnumberLessThanOrEqualTo(Integer value) {
            addCriterion("Killnumber <=", value, "killnumber");
            return (Criteria) this;
        }

        public Criteria andKillnumberIn(List<Integer> values) {
            addCriterion("Killnumber in", values, "killnumber");
            return (Criteria) this;
        }

        public Criteria andKillnumberNotIn(List<Integer> values) {
            addCriterion("Killnumber not in", values, "killnumber");
            return (Criteria) this;
        }

        public Criteria andKillnumberBetween(Integer value1, Integer value2) {
            addCriterion("Killnumber between", value1, value2, "killnumber");
            return (Criteria) this;
        }

        public Criteria andKillnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("Killnumber not between", value1, value2, "killnumber");
            return (Criteria) this;
        }

        public Criteria andDienumberIsNull() {
            addCriterion("Dienumber is null");
            return (Criteria) this;
        }

        public Criteria andDienumberIsNotNull() {
            addCriterion("Dienumber is not null");
            return (Criteria) this;
        }

        public Criteria andDienumberEqualTo(Integer value) {
            addCriterion("Dienumber =", value, "dienumber");
            return (Criteria) this;
        }

        public Criteria andDienumberNotEqualTo(Integer value) {
            addCriterion("Dienumber <>", value, "dienumber");
            return (Criteria) this;
        }

        public Criteria andDienumberGreaterThan(Integer value) {
            addCriterion("Dienumber >", value, "dienumber");
            return (Criteria) this;
        }

        public Criteria andDienumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("Dienumber >=", value, "dienumber");
            return (Criteria) this;
        }

        public Criteria andDienumberLessThan(Integer value) {
            addCriterion("Dienumber <", value, "dienumber");
            return (Criteria) this;
        }

        public Criteria andDienumberLessThanOrEqualTo(Integer value) {
            addCriterion("Dienumber <=", value, "dienumber");
            return (Criteria) this;
        }

        public Criteria andDienumberIn(List<Integer> values) {
            addCriterion("Dienumber in", values, "dienumber");
            return (Criteria) this;
        }

        public Criteria andDienumberNotIn(List<Integer> values) {
            addCriterion("Dienumber not in", values, "dienumber");
            return (Criteria) this;
        }

        public Criteria andDienumberBetween(Integer value1, Integer value2) {
            addCriterion("Dienumber between", value1, value2, "dienumber");
            return (Criteria) this;
        }

        public Criteria andDienumberNotBetween(Integer value1, Integer value2) {
            addCriterion("Dienumber not between", value1, value2, "dienumber");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberIsNull() {
            addCriterion("Assistsnumber is null");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberIsNotNull() {
            addCriterion("Assistsnumber is not null");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberEqualTo(Integer value) {
            addCriterion("Assistsnumber =", value, "assistsnumber");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberNotEqualTo(Integer value) {
            addCriterion("Assistsnumber <>", value, "assistsnumber");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberGreaterThan(Integer value) {
            addCriterion("Assistsnumber >", value, "assistsnumber");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("Assistsnumber >=", value, "assistsnumber");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberLessThan(Integer value) {
            addCriterion("Assistsnumber <", value, "assistsnumber");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberLessThanOrEqualTo(Integer value) {
            addCriterion("Assistsnumber <=", value, "assistsnumber");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberIn(List<Integer> values) {
            addCriterion("Assistsnumber in", values, "assistsnumber");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberNotIn(List<Integer> values) {
            addCriterion("Assistsnumber not in", values, "assistsnumber");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberBetween(Integer value1, Integer value2) {
            addCriterion("Assistsnumber between", value1, value2, "assistsnumber");
            return (Criteria) this;
        }

        public Criteria andAssistsnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("Assistsnumber not between", value1, value2, "assistsnumber");
            return (Criteria) this;
        }

        public Criteria andInjuryamountIsNull() {
            addCriterion("InjuryAmount is null");
            return (Criteria) this;
        }

        public Criteria andInjuryamountIsNotNull() {
            addCriterion("InjuryAmount is not null");
            return (Criteria) this;
        }

        public Criteria andInjuryamountEqualTo(Integer value) {
            addCriterion("InjuryAmount =", value, "injuryamount");
            return (Criteria) this;
        }

        public Criteria andInjuryamountNotEqualTo(Integer value) {
            addCriterion("InjuryAmount <>", value, "injuryamount");
            return (Criteria) this;
        }

        public Criteria andInjuryamountGreaterThan(Integer value) {
            addCriterion("InjuryAmount >", value, "injuryamount");
            return (Criteria) this;
        }

        public Criteria andInjuryamountGreaterThanOrEqualTo(Integer value) {
            addCriterion("InjuryAmount >=", value, "injuryamount");
            return (Criteria) this;
        }

        public Criteria andInjuryamountLessThan(Integer value) {
            addCriterion("InjuryAmount <", value, "injuryamount");
            return (Criteria) this;
        }

        public Criteria andInjuryamountLessThanOrEqualTo(Integer value) {
            addCriterion("InjuryAmount <=", value, "injuryamount");
            return (Criteria) this;
        }

        public Criteria andInjuryamountIn(List<Integer> values) {
            addCriterion("InjuryAmount in", values, "injuryamount");
            return (Criteria) this;
        }

        public Criteria andInjuryamountNotIn(List<Integer> values) {
            addCriterion("InjuryAmount not in", values, "injuryamount");
            return (Criteria) this;
        }

        public Criteria andInjuryamountBetween(Integer value1, Integer value2) {
            addCriterion("InjuryAmount between", value1, value2, "injuryamount");
            return (Criteria) this;
        }

        public Criteria andInjuryamountNotBetween(Integer value1, Integer value2) {
            addCriterion("InjuryAmount not between", value1, value2, "injuryamount");
            return (Criteria) this;
        }

        public Criteria andBearamountIsNull() {
            addCriterion("BearAmount is null");
            return (Criteria) this;
        }

        public Criteria andBearamountIsNotNull() {
            addCriterion("BearAmount is not null");
            return (Criteria) this;
        }

        public Criteria andBearamountEqualTo(Integer value) {
            addCriterion("BearAmount =", value, "bearamount");
            return (Criteria) this;
        }

        public Criteria andBearamountNotEqualTo(Integer value) {
            addCriterion("BearAmount <>", value, "bearamount");
            return (Criteria) this;
        }

        public Criteria andBearamountGreaterThan(Integer value) {
            addCriterion("BearAmount >", value, "bearamount");
            return (Criteria) this;
        }

        public Criteria andBearamountGreaterThanOrEqualTo(Integer value) {
            addCriterion("BearAmount >=", value, "bearamount");
            return (Criteria) this;
        }

        public Criteria andBearamountLessThan(Integer value) {
            addCriterion("BearAmount <", value, "bearamount");
            return (Criteria) this;
        }

        public Criteria andBearamountLessThanOrEqualTo(Integer value) {
            addCriterion("BearAmount <=", value, "bearamount");
            return (Criteria) this;
        }

        public Criteria andBearamountIn(List<Integer> values) {
            addCriterion("BearAmount in", values, "bearamount");
            return (Criteria) this;
        }

        public Criteria andBearamountNotIn(List<Integer> values) {
            addCriterion("BearAmount not in", values, "bearamount");
            return (Criteria) this;
        }

        public Criteria andBearamountBetween(Integer value1, Integer value2) {
            addCriterion("BearAmount between", value1, value2, "bearamount");
            return (Criteria) this;
        }

        public Criteria andBearamountNotBetween(Integer value1, Integer value2) {
            addCriterion("BearAmount not between", value1, value2, "bearamount");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountIsNull() {
            addCriterion("TreatmentAmount is null");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountIsNotNull() {
            addCriterion("TreatmentAmount is not null");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountEqualTo(Integer value) {
            addCriterion("TreatmentAmount =", value, "treatmentamount");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountNotEqualTo(Integer value) {
            addCriterion("TreatmentAmount <>", value, "treatmentamount");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountGreaterThan(Integer value) {
            addCriterion("TreatmentAmount >", value, "treatmentamount");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountGreaterThanOrEqualTo(Integer value) {
            addCriterion("TreatmentAmount >=", value, "treatmentamount");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountLessThan(Integer value) {
            addCriterion("TreatmentAmount <", value, "treatmentamount");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountLessThanOrEqualTo(Integer value) {
            addCriterion("TreatmentAmount <=", value, "treatmentamount");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountIn(List<Integer> values) {
            addCriterion("TreatmentAmount in", values, "treatmentamount");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountNotIn(List<Integer> values) {
            addCriterion("TreatmentAmount not in", values, "treatmentamount");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountBetween(Integer value1, Integer value2) {
            addCriterion("TreatmentAmount between", value1, value2, "treatmentamount");
            return (Criteria) this;
        }

        public Criteria andTreatmentamountNotBetween(Integer value1, Integer value2) {
            addCriterion("TreatmentAmount not between", value1, value2, "treatmentamount");
            return (Criteria) this;
        }

        public Criteria andMaketimeIsNull() {
            addCriterion("MakeTime is null");
            return (Criteria) this;
        }

        public Criteria andMaketimeIsNotNull() {
            addCriterion("MakeTime is not null");
            return (Criteria) this;
        }

        public Criteria andMaketimeEqualTo(Date value) {
            addCriterion("MakeTime =", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotEqualTo(Date value) {
            addCriterion("MakeTime <>", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeGreaterThan(Date value) {
            addCriterion("MakeTime >", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MakeTime >=", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeLessThan(Date value) {
            addCriterion("MakeTime <", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeLessThanOrEqualTo(Date value) {
            addCriterion("MakeTime <=", value, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeIn(List<Date> values) {
            addCriterion("MakeTime in", values, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotIn(List<Date> values) {
            addCriterion("MakeTime not in", values, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeBetween(Date value1, Date value2) {
            addCriterion("MakeTime between", value1, value2, "maketime");
            return (Criteria) this;
        }

        public Criteria andMaketimeNotBetween(Date value1, Date value2) {
            addCriterion("MakeTime not between", value1, value2, "maketime");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNull() {
            addCriterion("ModifyTime is null");
            return (Criteria) this;
        }

        public Criteria andModifytimeIsNotNull() {
            addCriterion("ModifyTime is not null");
            return (Criteria) this;
        }

        public Criteria andModifytimeEqualTo(Date value) {
            addCriterion("ModifyTime =", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotEqualTo(Date value) {
            addCriterion("ModifyTime <>", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThan(Date value) {
            addCriterion("ModifyTime >", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ModifyTime >=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThan(Date value) {
            addCriterion("ModifyTime <", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeLessThanOrEqualTo(Date value) {
            addCriterion("ModifyTime <=", value, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeIn(List<Date> values) {
            addCriterion("ModifyTime in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotIn(List<Date> values) {
            addCriterion("ModifyTime not in", values, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeBetween(Date value1, Date value2) {
            addCriterion("ModifyTime between", value1, value2, "modifytime");
            return (Criteria) this;
        }

        public Criteria andModifytimeNotBetween(Date value1, Date value2) {
            addCriterion("ModifyTime not between", value1, value2, "modifytime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jbsigleplayer
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 27 21:34:56 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jbsigleplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}