package com.jtm.dto;

import java.util.Date;

public class JBSiglePlayer extends JBSiglePlayerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Playername
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String playername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Matchteam
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String matchteam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Playerheroid
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Integer playerheroid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Playerhero
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String playerhero;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Playerskill1
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String playerskill1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Playerskill2
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String playerskill2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Ornament
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String ornament;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Equipment1
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String equipment1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Equipment2
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String equipment2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Equipment3
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String equipment3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Equipment4
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String equipment4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Equipment5
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String equipment5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Equipment6
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private String equipment6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Killnumber
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Integer killnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Dienumber
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Integer dienumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.Assistsnumber
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Integer assistsnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.InjuryAmount
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Integer injuryamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.BearAmount
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Integer bearamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.TreatmentAmount
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Integer treatmentamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.MakeTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Date maketime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbsigleplayer.ModifyTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Playername
     *
     * @return the value of jbsigleplayer.Playername
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getPlayername() {
        return playername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Playername
     *
     * @param playername the value for jbsigleplayer.Playername
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setPlayername(String playername) {
        this.playername = playername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Matchteam
     *
     * @return the value of jbsigleplayer.Matchteam
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getMatchteam() {
        return matchteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Matchteam
     *
     * @param matchteam the value for jbsigleplayer.Matchteam
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setMatchteam(String matchteam) {
        this.matchteam = matchteam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Playerheroid
     *
     * @return the value of jbsigleplayer.Playerheroid
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Integer getPlayerheroid() {
        return playerheroid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Playerheroid
     *
     * @param playerheroid the value for jbsigleplayer.Playerheroid
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setPlayerheroid(Integer playerheroid) {
        this.playerheroid = playerheroid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Playerhero
     *
     * @return the value of jbsigleplayer.Playerhero
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getPlayerhero() {
        return playerhero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Playerhero
     *
     * @param playerhero the value for jbsigleplayer.Playerhero
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setPlayerhero(String playerhero) {
        this.playerhero = playerhero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Playerskill1
     *
     * @return the value of jbsigleplayer.Playerskill1
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getPlayerskill1() {
        return playerskill1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Playerskill1
     *
     * @param playerskill1 the value for jbsigleplayer.Playerskill1
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setPlayerskill1(String playerskill1) {
        this.playerskill1 = playerskill1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Playerskill2
     *
     * @return the value of jbsigleplayer.Playerskill2
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getPlayerskill2() {
        return playerskill2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Playerskill2
     *
     * @param playerskill2 the value for jbsigleplayer.Playerskill2
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setPlayerskill2(String playerskill2) {
        this.playerskill2 = playerskill2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Ornament
     *
     * @return the value of jbsigleplayer.Ornament
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getOrnament() {
        return ornament;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Ornament
     *
     * @param ornament the value for jbsigleplayer.Ornament
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setOrnament(String ornament) {
        this.ornament = ornament;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Equipment1
     *
     * @return the value of jbsigleplayer.Equipment1
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getEquipment1() {
        return equipment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Equipment1
     *
     * @param equipment1 the value for jbsigleplayer.Equipment1
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setEquipment1(String equipment1) {
        this.equipment1 = equipment1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Equipment2
     *
     * @return the value of jbsigleplayer.Equipment2
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getEquipment2() {
        return equipment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Equipment2
     *
     * @param equipment2 the value for jbsigleplayer.Equipment2
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setEquipment2(String equipment2) {
        this.equipment2 = equipment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Equipment3
     *
     * @return the value of jbsigleplayer.Equipment3
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getEquipment3() {
        return equipment3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Equipment3
     *
     * @param equipment3 the value for jbsigleplayer.Equipment3
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setEquipment3(String equipment3) {
        this.equipment3 = equipment3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Equipment4
     *
     * @return the value of jbsigleplayer.Equipment4
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getEquipment4() {
        return equipment4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Equipment4
     *
     * @param equipment4 the value for jbsigleplayer.Equipment4
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setEquipment4(String equipment4) {
        this.equipment4 = equipment4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Equipment5
     *
     * @return the value of jbsigleplayer.Equipment5
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getEquipment5() {
        return equipment5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Equipment5
     *
     * @param equipment5 the value for jbsigleplayer.Equipment5
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setEquipment5(String equipment5) {
        this.equipment5 = equipment5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Equipment6
     *
     * @return the value of jbsigleplayer.Equipment6
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public String getEquipment6() {
        return equipment6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Equipment6
     *
     * @param equipment6 the value for jbsigleplayer.Equipment6
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setEquipment6(String equipment6) {
        this.equipment6 = equipment6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Killnumber
     *
     * @return the value of jbsigleplayer.Killnumber
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Integer getKillnumber() {
        return killnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Killnumber
     *
     * @param killnumber the value for jbsigleplayer.Killnumber
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setKillnumber(Integer killnumber) {
        this.killnumber = killnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Dienumber
     *
     * @return the value of jbsigleplayer.Dienumber
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Integer getDienumber() {
        return dienumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Dienumber
     *
     * @param dienumber the value for jbsigleplayer.Dienumber
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setDienumber(Integer dienumber) {
        this.dienumber = dienumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.Assistsnumber
     *
     * @return the value of jbsigleplayer.Assistsnumber
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Integer getAssistsnumber() {
        return assistsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.Assistsnumber
     *
     * @param assistsnumber the value for jbsigleplayer.Assistsnumber
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setAssistsnumber(Integer assistsnumber) {
        this.assistsnumber = assistsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.InjuryAmount
     *
     * @return the value of jbsigleplayer.InjuryAmount
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Integer getInjuryamount() {
        return injuryamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.InjuryAmount
     *
     * @param injuryamount the value for jbsigleplayer.InjuryAmount
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setInjuryamount(Integer injuryamount) {
        this.injuryamount = injuryamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.BearAmount
     *
     * @return the value of jbsigleplayer.BearAmount
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Integer getBearamount() {
        return bearamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.BearAmount
     *
     * @param bearamount the value for jbsigleplayer.BearAmount
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setBearamount(Integer bearamount) {
        this.bearamount = bearamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.TreatmentAmount
     *
     * @return the value of jbsigleplayer.TreatmentAmount
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Integer getTreatmentamount() {
        return treatmentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.TreatmentAmount
     *
     * @param treatmentamount the value for jbsigleplayer.TreatmentAmount
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setTreatmentamount(Integer treatmentamount) {
        this.treatmentamount = treatmentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.MakeTime
     *
     * @return the value of jbsigleplayer.MakeTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Date getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.MakeTime
     *
     * @param maketime the value for jbsigleplayer.MakeTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbsigleplayer.ModifyTime
     *
     * @return the value of jbsigleplayer.ModifyTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbsigleplayer.ModifyTime
     *
     * @param modifytime the value for jbsigleplayer.ModifyTime
     *
     * @mbg.generated Thu Jan 31 16:25:24 CST 2019
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}