package com.jtm.dto;

import java.util.Date;

public class JBUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbuser.UserId
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbuser.Name
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbuser.UserName
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbuser.PassWords
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    private String passwords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbuser.LastLoginDate
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    private Date lastlogindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbuser.LastLoginTime
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    private String lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbuser.MakeDate
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    private Date makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbuser.MakeTime
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    private String maketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbuser.ModifyDate
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jbuser.ModifyTime
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    private String modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbuser.UserId
     *
     * @return the value of jbuser.UserId
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbuser.UserId
     *
     * @param userid the value for jbuser.UserId
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbuser.Name
     *
     * @return the value of jbuser.Name
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbuser.Name
     *
     * @param name the value for jbuser.Name
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbuser.UserName
     *
     * @return the value of jbuser.UserName
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbuser.UserName
     *
     * @param username the value for jbuser.UserName
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbuser.PassWords
     *
     * @return the value of jbuser.PassWords
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public String getPasswords() {
        return passwords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbuser.PassWords
     *
     * @param passwords the value for jbuser.PassWords
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbuser.LastLoginDate
     *
     * @return the value of jbuser.LastLoginDate
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public Date getLastlogindate() {
        return lastlogindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbuser.LastLoginDate
     *
     * @param lastlogindate the value for jbuser.LastLoginDate
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public void setLastlogindate(Date lastlogindate) {
        this.lastlogindate = lastlogindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbuser.LastLoginTime
     *
     * @return the value of jbuser.LastLoginTime
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public String getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbuser.LastLoginTime
     *
     * @param lastlogintime the value for jbuser.LastLoginTime
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public void setLastlogintime(String lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbuser.MakeDate
     *
     * @return the value of jbuser.MakeDate
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbuser.MakeDate
     *
     * @param makedate the value for jbuser.MakeDate
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbuser.MakeTime
     *
     * @return the value of jbuser.MakeTime
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public String getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbuser.MakeTime
     *
     * @param maketime the value for jbuser.MakeTime
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public void setMaketime(String maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbuser.ModifyDate
     *
     * @return the value of jbuser.ModifyDate
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbuser.ModifyDate
     *
     * @param modifydate the value for jbuser.ModifyDate
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jbuser.ModifyTime
     *
     * @return the value of jbuser.ModifyTime
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public String getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jbuser.ModifyTime
     *
     * @param modifytime the value for jbuser.ModifyTime
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    public void setModifytime(String modifytime) {
        this.modifytime = modifytime;
    }
}