server:
  port: 9003
spring:
  application:
    name: jtm-service-zuul
  security:
    user:
      name: javatv
      password: javatv
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:9000/eureka/
zuul:
  routes:
    api-a:
      path: /match/**
      serviceId: jtm-match-service
    api-b:
      path: /query/**
      serviceId: jtm-query-service