package com.jtm.mapper;

import com.jtm.dto.JBUser;
import com.jtm.dto.JBUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JBUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    int countByExample(JBUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    int deleteByExample(JBUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    int insert(JBUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    int insertSelective(JBUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    List<JBUser> selectByExample(JBUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    JBUser selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") JBUser record, @Param("example") JBUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    int updateByExample(@Param("record") JBUser record, @Param("example") JBUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    int updateByPrimaryKeySelective(JBUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbuser
     *
     * @mbggenerated Wed Nov 27 22:28:23 CST 2019
     */
    int updateByPrimaryKey(JBUser record);
}