spring: 
  application: 
    name: ${jtm.application.name}
  datasource:
    type: ${jtm.datasource.type}
    driver-class-name: ${jtm.datasource.driver-class-name}
    username: ${jtm.datasource.username}
    password: ${jtm.datasource.password}
    initialSize:
    dbcp2:
      min-idle: 5
    url: ${jtm.datasource.url}
server: 
  port: ${jtm.server.port}
  