package com.jtm.mapper;

import com.jtm.dto.JBMatch;
import com.jtm.dto.JBMatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JBMatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int countByExample(JBMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int deleteByExample(JBMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int deleteByPrimaryKey(Integer matchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int insert(JBMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int insertSelective(JBMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    List<JBMatch> selectByExample(JBMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    JBMatch selectByPrimaryKey(Integer matchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") JBMatch record, @Param("example") JBMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int updateByExample(@Param("record") JBMatch record, @Param("example") JBMatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int updateByPrimaryKeySelective(JBMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbmatch
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int updateByPrimaryKey(JBMatch record);
}