package com.jtm.mapper;

import com.jtm.dto.JBPlayer;
import com.jtm.dto.JBPlayerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JBPlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int countByExample(JBPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int deleteByExample(JBPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int deleteByPrimaryKey(Integer playerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int insert(JBPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int insertSelective(JBPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    List<JBPlayer> selectByExample(JBPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    JBPlayer selectByPrimaryKey(Integer playerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") JBPlayer record, @Param("example") JBPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int updateByExample(@Param("record") JBPlayer record, @Param("example") JBPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int updateByPrimaryKeySelective(JBPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jbplayer
     *
     * @mbggenerated Wed Nov 27 21:34:56 CST 2019
     */
    int updateByPrimaryKey(JBPlayer record);
}