server:
  port: 9001
spring: 
  application:
    name: jtm-config-service
  security: 
    user:
      name: javatv
      password: javatv
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Casoo7/javatv.git
          search-paths: config-repo
          username: 
          password: 
        default-label: master
      label: master
eureka: 
  instance:
    hostname: localhost
  client: 
    service-url: 
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:9000/eureka/
        